import { DesignToolHookResultSchema } from '@molly/shared/local-machine-rpc';
/**
 * Availability of the built-in design tools (P2.4).
 *
 * `molly_generate_image` and `molly_edit_image` are registered only when the asking session is a design
 * session AND this machine has a complete, enabled image connection. Both
 * halves matter: the tool writes generated bytes into the session workdir, and a
 * coding session's workdir is the user's own project repository. The decision
 * belongs to the daemon, which owns the per-machine Flock row and the session
 * metadata; the built-in MCP server asks for it over the same machine-local
 * control socket it already uses for `session/get-active-invocation-context`,
 * rather than opening storage of its own (which would cost a second writer on
 * the machine's SQLite store for a one-row read, and would make the answer
 * depend on the MCP process's own view of a document the daemon is the
 * authority for).
 *
 * The credential travels with that answer and only with that answer: the socket
 * is owner-only, on the same machine, and the MCP server is the daemon's own
 * child running as the same user. It never reaches an MCP server config, an
 * environment variable, a header, or a log line — see the note on the RPC
 * result schema.
 *
 * Absence is the default and every failure resolves to it: a daemon that cannot
 * be reached is not a daemon that said yes, and a session the daemon cannot
 * recognize as a design session is not one. A missing tool is honest, while a
 * registered tool that always errors would teach the agent to stop trying.
 *
 * `molly_render_preview` (P2.4b) rides the same socket for the same reason, but
 * asks a different question: whether a Molly desktop is polling this machine. It
 * is the desktop — not the daemon — that owns rendering, so the capability this
 * tool needs is not a credential the daemon holds but a window the user has
 * open. The two gates stay separate fields because they are separate facts, and
 * the render request itself is also the honest one: the daemon renders from the
 * session workdir it already resolves, so this process never learns a path it
 * could have supplied.
 */

import {
  DesignRenderRpcResultSchema,
  ImageConnectionRpcResultSchema,
  normalizeImageConnectionSettings,
  isImageConnectionReady,
  type ImageConnectionSettings,
  type SessionId,
} from '@molly/shared';
import { makeLocalControlClientAuto } from '@molly/shared/node/local-ipc';
import { Effect } from 'effect';

/** How long the gate lookup may take before it is treated as "no capability". */
export const DESIGN_GATE_TIMEOUT_MS = 10_000;

/**
 * How long the render call itself may take.
 *
 * Deliberately longer than the daemon's own preview timeout (60 s,
 * `DESIGN_RENDER_PREVIEW_TIMEOUT_MS`): the daemon must be the one that gives up
 * first, so that a slow render resolves as an honest daemon-side refusal
 * ("nothing rendered am I willing to hand over") instead of this process
 * abandoning a call the daemon is still holding. A client that times out first
 * would leave the daemon's queue holding work for a preview nobody is waiting
 * for.
 */
export const DESIGN_RENDER_TIMEOUT_MS = 75_000;

/**
 * What the built-in MCP server needs to know about design capability.
 *
 * A snapshot taken when the server is built, and refreshed before each paid
 * call: the MCP server is constructed per turn on the HTTP transport and once
 * per session on stdio, so a settings change reaches the tool without a restart
 * on the first path and no later than the next session on the second.
 */
export type McpDesignGate = {
  /**
   * `null` unless the asking session is a design session and the machine has a
   * complete, enabled connection; the daemon decides both and folds them into
   * the same answer, so no caller can register the tool on half the condition.
   */
  imageConnection: ImageConnectionSettings | null;
  /** Public discovery snapshot; never sufficient to execute a paid request. */
  imageAvailable?: boolean;
  /** Resolved by the daemon from the live Session; never a caller-selected root. */
  artworkWorkdir?: string;
  workspaceRoot?: string;
};

export const EMPTY_DESIGN_GATE: McpDesignGate = { imageConnection: null };

export type DesignGateContext = {
  designHookLaunchId?: string;
  machineId: string;
  workspaceId: string;
  /** The asking session; sent as `ownerSessionId` so the daemon can apply the design-session rule. */
  sessionId: SessionId;
  localControlSocketPath: string | undefined;
};

const errorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

/**
 * Turn one daemon answer into a gate — the single place that decides what
 * counts as capability.
 *
 * `ready` already folds in the design-session rule (the daemon applies it, and
 * only the daemon can), so this is deliberately a pure reading of the answer:
 * an unexpected shape, a non-design session, or a connection that is absent,
 * switched off, or keyless all become the same empty gate.
 */
export function designGateFromRpcResult(result: unknown): McpDesignGate {
  const parsed = ImageConnectionRpcResultSchema.safeParse(result);
  if (!parsed.success || parsed.data.type !== 'design/image-connection') {
    return EMPTY_DESIGN_GATE;
  }
  const { connection, ready, credential } = parsed.data;
  if (
    parsed.data.available &&
    connection?.enabled &&
    connection.hasApiKey &&
    parsed.data.artworkWorkdir &&
    parsed.data.workspaceRoot &&
    (!ready || !credential)
  ) {
    return {
      imageConnection: null,
      imageAvailable: true,
      artworkWorkdir: parsed.data.artworkWorkdir,
      workspaceRoot: parsed.data.workspaceRoot,
    };
  }
  if (
    !ready ||
    connection === null ||
    credential === null ||
    !parsed.data.artworkWorkdir ||
    !parsed.data.workspaceRoot
  ) {
    return EMPTY_DESIGN_GATE;
  }
  const settings = normalizeImageConnectionSettings({
    v: 1,
    ...connection,
    apiKey: credential.apiKey,
  });
  return isImageConnectionReady(settings)
    ? {
        imageConnection: settings,
        ...(parsed.data.artworkWorkdir ? { artworkWorkdir: parsed.data.artworkWorkdir } : {}),
        ...(parsed.data.workspaceRoot ? { workspaceRoot: parsed.data.workspaceRoot } : {}),
      }
    : EMPTY_DESIGN_GATE;
}

/**
 * Ask the daemon whether image capability exists for this session, and for the
 * connection when it does. Never throws: every failure is a gate that says "not
 * available".
 *
 * `ownerSessionId` is how the daemon applies the design-session half of the
 * rule: the request carries the asking session, and the answer folds session
 * kind and connection readiness into one `ready` bit and one credential. The
 * MCP server therefore never judges session kind itself — it could not, and a
 * second judgment would be a second thing to keep in sync.
 */
export async function resolveDesignGate(
  ctx: DesignGateContext,
  logger?: { debug(message: string): void },
  acquireCredential = false
): Promise<McpDesignGate> {
  if (!ctx.localControlSocketPath) {
    logger?.debug('design gate: no local control socket; image tool stays unregistered');
    return EMPTY_DESIGN_GATE;
  }
  const answer = await callDesignRpc(ctx, logger, 'design/image-connection', { acquireCredential });
  if (!answer.ok) {
    logger?.debug(`design gate: lookup failed: ${answer.error}`);
    return EMPTY_DESIGN_GATE;
  }
  const gate = designGateFromRpcResult(answer.result);
  if (gate.imageConnection === null) {
    logger?.debug(
      'design gate: session is not an eligible design session, or the image connection is absent, disabled, or incomplete'
    );
  }
  return gate;
}

/**
 * Whether a Molly desktop is polling the daemon right now, which is the whole
 * of what makes preview rendering possible (P2.4b).
 *
 * Separate from `resolveDesignGate` because the two capabilities are genuinely
 * independent: a machine can have a working image connection with no desktop
 * running, and a desktop can be running with no image connection at all.
 * Folding them into one bit would make either tool lie about the other.
 */
export async function resolveRenderHost(
  ctx: DesignGateContext,
  logger?: { debug(message: string): void }
): Promise<boolean> {
  if (!ctx.localControlSocketPath) {
    logger?.debug('render gate: no local control socket; preview tool stays unregistered');
    return false;
  }
  const answer = await callDesignRpc(ctx, logger, 'design/render-host-status', {});
  if (!answer.ok) {
    logger?.debug(`render gate: daemon refused the lookup: ${answer.error}`);
    return false;
  }
  const connected = renderHostFromRpcResult(answer.result);
  if (!connected) {
    logger?.debug('render gate: no Molly desktop is polling this machine, so nothing can render');
  }
  return connected;
}

/** The daemon's own reading of `design/render-host-status`; anything else is "no". */
export function renderHostFromRpcResult(result: unknown): boolean {
  const parsed = DesignRenderRpcResultSchema.safeParse(result);
  if (!parsed.success || parsed.data.type !== 'design/render-host-status') return false;
  return parsed.data.connected;
}

export type DesignRenderRequest =
  | { status: 'rendered'; path: string; width: number; height: number; bytes: number }
  | { status: 'refused'; error: string };

/**
 * Ask the daemon to render one preview of the asking session's project.
 *
 * The daemon owns the workdir, the intake, and the render queue; this process
 * owns nothing but the question. Every answer — including "the desktop went
 * away mid-render" — comes back as a result, because none of those are
 * transport failures: a preview that could not be rendered is a fact the agent
 * is entitled to hear.
 */
export async function requestDesignRenderPreview(
  ctx: DesignGateContext,
  logger?: { debug(message: string): void }
): Promise<DesignRenderRequest> {
  if (!ctx.localControlSocketPath) {
    return { status: 'refused', error: 'this session has no local control socket to ask.' };
  }
  const answer = await callDesignRpc(
    ctx,
    logger,
    'design/render-preview',
    {},
    DESIGN_RENDER_TIMEOUT_MS
  );
  if (!answer.ok) return { status: 'refused', error: answer.error };

  const parsed = DesignRenderRpcResultSchema.safeParse(answer.result);
  if (!parsed.success || parsed.data.type !== 'design/render-preview') {
    return { status: 'refused', error: 'the daemon answered the render request unexpectedly.' };
  }
  return parsed.data.ok
    ? {
        status: 'rendered',
        path: parsed.data.path,
        width: parsed.data.width,
        height: parsed.data.height,
        bytes: parsed.data.bytes,
      }
    : { status: 'refused', error: parsed.data.error };
}

type DesignRpcAnswer = { ok: true; result: unknown } | { ok: false; error: string };

/**
 * One question to the daemon over the machine-local control socket.
 *
 * Never throws: a missing socket, a timeout, a protocol surprise, or a refusal
 * envelope all become the same "not available", because absence is what every
 * caller here already means by a failed lookup.
 */
async function callDesignRpc(
  ctx: DesignGateContext,
  logger: { debug(message: string): void } | undefined,
  method: 'design/image-connection' | 'design/render-host-status' | 'design/render-preview',
  params: { acquireCredential?: boolean },
  timeoutMs: number = DESIGN_GATE_TIMEOUT_MS
): Promise<DesignRpcAnswer> {
  const socketPath = ctx.localControlSocketPath;
  if (!socketPath) return { ok: false, error: 'no local control socket' };
  try {
    const result = await Effect.runPromise(
      makeLocalControlClientAuto({ socketPath })
        .machineRpc(
          {
            machineId: ctx.machineId,
            workspaceId: ctx.workspaceId,
            ownerSessionId: ctx.sessionId,
            ...(method === 'design/image-connection' ? { method, params } : { method, params: {} }),
          },
          { timeoutMs }
        )
        .pipe(
          Effect.catchTag('IpcTimeoutError', (error) =>
            Effect.fail(
              new Error(`local control timed out after ${timeoutMs}ms (${error.message})`)
            )
          ),
          Effect.catchTag('IpcProtocolError', (error) =>
            Effect.fail(new Error(error.message, { cause: error }))
          )
        )
    );
    if (!result.ok) return { ok: false, error: result.error };
    return { ok: true, result: result.result };
  } catch (error) {
    logger?.debug(`design rpc ${method} failed: ${errorMessage(error)}`);
    return { ok: false, error: errorMessage(error) };
  }
}

export async function requestDesignResubmit(
  context: DesignGateContext,
  input?: { expectedRevisionId: string; artifactDigest: string }
) {
  const response = await Effect.runPromise(
    makeLocalControlClientAuto({ socketPath: context.localControlSocketPath }).machineRpc(
      {
        method: 'design/tool-hook',
        machineId: context.machineId,
        workspaceId: context.workspaceId,
        ownerSessionId: context.sessionId,
        params: {
          version: 2,
          launchId: context.designHookLaunchId,
          event: input ? { phase: 'resubmit', ...input } : { phase: 'resubmit-capability' },
        },
      },
      { timeoutMs: DESIGN_GATE_TIMEOUT_MS }
    )
  );
  if (!response.ok) throw Error(response.error);
  const answer = DesignToolHookResultSchema.parse(response.result);
  if (!answer.ok) throw Error(answer.error ?? 'Design resubmission unavailable');
  return answer.supported;
}

export async function resolveDesignResubmit(context: DesignGateContext) {
  return requestDesignResubmit(context).catch(() => false);
}
