import { mkdirSync } from 'fs';
import path from 'path';
import { getMollyDataDir } from '@molly/shared/node/installation-profile';

import { getGhShimHostBinDir } from './gh-shim-script';
import {
  normalizeComparablePath,
  toSingleQuotedShellString,
  writeIfChanged,
} from './shell-file-utils';

const MOLLY_BASH_ENV_PATH = path.join(getMollyDataDir(), 'bashenv');

const buildBashEnvSource = (
  ghShimBinDir: string,
  inheritBashEnv: string | undefined,
  currentBashEnvPath: string
): string => {
  const shouldSourceInherited =
    inheritBashEnv &&
    normalizeComparablePath(inheritBashEnv) !== normalizeComparablePath(currentBashEnvPath);
  const sourceInherited = shouldSourceInherited
    ? `if [ -f ${toSingleQuotedShellString(inheritBashEnv)} ]; then
  . ${toSingleQuotedShellString(inheritBashEnv)}
fi

`
    : '';

  return `# Auto-generated by Molly for gh wrapper support.
${sourceInherited}export PATH=${toSingleQuotedShellString(ghShimBinDir)}:"$PATH"
`;
};

export const shouldInjectBashEnvForGhShim = (): boolean => process.platform !== 'win32';

export const ensureMollyBashEnvForGhShim = (inheritBashEnv?: string): string => {
  const bashEnvPath = MOLLY_BASH_ENV_PATH;
  mkdirSync(path.dirname(bashEnvPath), { recursive: true });
  writeIfChanged(
    bashEnvPath,
    buildBashEnvSource(getGhShimHostBinDir(), inheritBashEnv, bashEnvPath)
  );
  return bashEnvPath;
};
