#!/usr/bin/env node
/**
 * Build script for @molly/design-authoring.
 *
 * 1. Verifies source-manifest.json: every verbatim-migrated file must exist and
 *    match its recorded sha256 (adapted files record upstream provenance only).
 * 2. Embeds the vendored frozen capability matrix
 *    (packages/design-bento/vendor/.../capability-matrix/v1.json) as base64 into
 *    src/generated/capability-matrix-bytes.ts so the matrix survives bundling.
 *    The expected hash is extracted from the vendored contracts matrix.ts
 *    (FROZEN_MATRIX_SHA256) — the vendored kernel snapshot stays the single
 *    truth — and the v1.json bytes must match it, fail-closed.
 * 3. Bundles the skill script support library with esbuild into
 *    skills/graphic-design/scripts/lib/molly-authoring.mjs so the materialized
 *    skill directory is self-contained (no repo checkout, no node_modules).
 *    Live helper, Folio wording, rewritten skills, and PPTD catalogues must
 *    not remain named after the retired format or pinned as live ALD upstream.
 *
 * Run before typecheck/test (package scripts do this) and before the CLI
 * stages skill directories (apps/cli prepare:design-authoring).
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(packageRoot, '..', '..');

const sha256Hex = (bytes) => createHash('sha256').update(bytes).digest('hex');

function fail(message) {
  console.error(`design-authoring build: ${message}`);
  process.exit(1);
}

// ---- 1. source manifest verification ----

const manifestPath = path.join(packageRoot, 'source-manifest.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

const manifestText = JSON.stringify(manifest);
if (/\bFolio\b/.test(manifestText)) fail('source-manifest still contains Folio wording');
const unpinnedLiveRows = [
  'skills/graphic-design/SKILL.md',
  'skills/graphic-design/scripts/finalize.mjs',
  'skills/graphic-design/scripts/render-preview.mjs',
  'skills/graphic-design/references/pptd-authoring.md',
  'skills/graphic-design/examples/minimal/poster.pptd',
  'skills/graphic-design/examples/minimal/pages/poster.page',
  'skills/imagegen/SKILL.md',
];
for (const relpath of unpinnedLiveRows) {
  if (manifest.files[relpath] !== undefined) {
    fail(`rewritten skill or PPTD catalogue still pinned as live upstream: ${relpath}`);
  }
}

for (const [relpath, entry] of Object.entries(manifest.files)) {
  const abs = path.join(packageRoot, relpath);
  if (!existsSync(abs)) fail(`manifest file missing: ${relpath}`);
  if (entry.derivation === 'rewritten') {
    fail(`rewritten authoring skill still pinned as live upstream: ${relpath}`);
  }
  if (
    String(relpath).toLowerCase().includes('pptd') &&
    (entry.derivation === 'verbatim' || entry.derivation === 'adapted')
  ) {
    fail(`PPTD catalogue still pinned as live ALD upstream: ${relpath}`);
  }
  if (entry.derivation === 'verbatim') {
    const actual = sha256Hex(readFileSync(abs));
    if (actual !== entry.sha256) {
      fail(
        `verbatim file drifted from pinned upstream: ${relpath} (expected ${entry.sha256}, got ${actual})`
      );
    }
  }
}

// ---- 2. capability matrix embedding ----

const vendorContracts = path.join(
  repoRoot,
  'packages',
  'design-bento',
  'vendor',
  'packages',
  'contracts'
);
const matrixTs = readFileSync(path.join(vendorContracts, 'src', 'matrix.ts'), 'utf8');
const frozenMatch = /FROZEN_MATRIX_SHA256 = "([0-9a-f]{64})"/.exec(matrixTs);
if (frozenMatch === null) fail('FROZEN_MATRIX_SHA256 not found in vendored contracts matrix.ts');
const frozenSha256 = frozenMatch[1];

const matrixRel = manifest.capabilityMatrix.path;
const matrixBytes = readFileSync(path.join(packageRoot, matrixRel));
const matrixSha256 = sha256Hex(matrixBytes);
if (matrixSha256 !== frozenSha256 || matrixSha256 !== manifest.capabilityMatrix.sha256) {
  fail(
    `capability matrix hash mismatch: vendored v1.json is ${matrixSha256}, ` +
      `contracts constant ${frozenSha256}, manifest ${manifest.capabilityMatrix.sha256}`
  );
}

const generatedDir = path.join(packageRoot, 'src', 'generated');
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  path.join(generatedDir, 'capability-matrix-bytes.ts'),
  `/**\n * GENERATED by scripts/build.mjs — do not edit.\n *\n * Base64 of the vendored frozen capability matrix\n * (packages/design-bento/vendor/packages/contracts/capability-matrix/v1.json,\n * sha256 ${matrixSha256}). Runtime consumers re-verify the\n * decoded bytes against FROZEN_MATRIX_SHA256 before parsing.\n */\n\nexport const CAPABILITY_MATRIX_V1_BASE64 =\n  '${matrixBytes.toString('base64')}';\n`
);

// ---- 3. skill script support bundle ----

const helperDir = path.join(packageRoot, 'skills', 'graphic-design', 'scripts', 'lib');
const helperOut = path.join(helperDir, 'molly-authoring.mjs');
const staleHelperNames = ['geon-pptd.mjs', 'geon-authoring.mjs'];
if (staleHelperNames.includes(path.basename(helperOut)))
  fail('live helper bundle must not use a pre-rename name');
for (const staleName of staleHelperNames) {
  const staleHelper = path.join(helperDir, staleName);
  if (existsSync(staleHelper)) rmSync(staleHelper);
}

const { build } = await import('esbuild');
await build({
  entryPoints: [path.join(packageRoot, 'src', 'index.ts')],
  outfile: helperOut,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  // Node builtins stay external; everything else (vendored contracts, yaml,
  // generated matrix bytes) is inlined for a self-contained skill dir.
  packages: 'bundle',
  // Bundled CJS deps (yaml) keep dynamic require calls; provide a real
  // require in the ESM output.
  banner: {
    js: "import { createRequire as __mollyCreateRequire } from 'node:module'; const require = __mollyCreateRequire(import.meta.url);",
  },
  logLevel: 'warning',
});

// The vendored text default names the upstream face; the design canvas
// (design-bento build) rewrites it to the bundled Inter face. Skill-side
// authoring and validation must bless the same registration-optional default,
// so apply the identical adaptation to the assembled helper bundle.
const helper = readFileSync(helperOut, 'utf8');
if (helper.split('fontFamily: "MiSans",').length !== 2)
  fail('Pinned text font default changed; review the Inter adaptation');
writeFileSync(helperOut, helper.replace('fontFamily: "MiSans",', 'fontFamily: "Inter",'));

console.log('design-authoring build: ok');
