// Generated by scripts/generate-ui-icons.mjs. Edit svg/*.svg, then run pnpm icons:generate.
import type { UiIconNode } from './types';

export const activityIcon = [
  ['path', { d: 'M3.8 12h3.4l2.2-6.8 4.5 13.6 2.4-6.8h3.9' }],
] as const satisfies readonly UiIconNode[];

export const alarmClockIcon = [
  ['circle', { cx: '12', cy: '13', r: '7.1' }],
  ['path', { d: 'M5.9 3.8 3.9 5.8m14.2-2 2 2M7 19.1l-1.2 1.1m11.2-1.1 1.2 1.1M12 8.8V13l2.9 1.8' }],
] as const satisfies readonly UiIconNode[];

export const alignCenterIcon = [
  ['path', { d: 'M4.5 5.5h15M7 10h10M4.5 14.5h15M7 19h10' }],
] as const satisfies readonly UiIconNode[];

export const alignJustifyIcon = [
  ['path', { d: 'M4.5 5.5h15M4.5 10h15M4.5 14.5h15M4.5 19h15' }],
] as const satisfies readonly UiIconNode[];

export const alignLeftIcon = [
  ['path', { d: 'M4.5 5.5h15M4.5 10h10M4.5 14.5h15M4.5 19h10' }],
] as const satisfies readonly UiIconNode[];

export const alignRightIcon = [
  ['path', { d: 'M4.5 5.5h15M9.5 10h10M4.5 14.5h15M9.5 19h10' }],
] as const satisfies readonly UiIconNode[];

export const archiveIcon = [
  ['rect', { x: '3.5', y: '4.5', width: '17', height: '4.5', rx: '2' }],
  ['path', { d: 'M5 9v9a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V9' }],
  ['line', { x1: '10', y1: '12.5', x2: '14', y2: '12.5' }],
] as const satisfies readonly UiIconNode[];

export const archiveRestoreIcon = [
  ['rect', { x: '3.5', y: '4.5', width: '17', height: '4.5', rx: '2' }],
  ['path', { d: 'M5 9v9a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V9' }],
  ['path', { d: 'M12 17v-5.5m-2.5 2.5 2.5-2.5 2.5 2.5' }],
] as const satisfies readonly UiIconNode[];

export const arrowDownIcon = [
  ['path', { d: 'M12 4.5v15m-5-5 5 5 5-5' }],
] as const satisfies readonly UiIconNode[];

export const arrowDownAZIcon = [
  [
    'path',
    { d: 'M4.7 10.2 7.2 4.8l2.5 5.4M5.8 8.3h2.8M4.7 14h5l-5 5.5h5M17.2 4.8v14.7m-3-3 3 3 3-3' },
  ],
] as const satisfies readonly UiIconNode[];

export const arrowLeftIcon = [
  ['path', { d: 'M19.5 12h-15m5-5-5 5 5 5' }],
] as const satisfies readonly UiIconNode[];

export const arrowRightIcon = [
  ['path', { d: 'M4.5 12h15m-5-5 5 5-5 5' }],
] as const satisfies readonly UiIconNode[];

export const arrowShapeIcon = [
  ['path', { d: 'M4 9.5h9v-4l7 6.5-7 6.5v-4H4v-5Z' }],
] as const satisfies readonly UiIconNode[];

export const arrowUpIcon = [
  ['path', { d: 'M12 19.5v-15m-5 5 5-5 5 5' }],
] as const satisfies readonly UiIconNode[];

export const arrowUpDownIcon = [
  ['path', { d: 'M7.8 19.5v-15m-3 3 3-3 3 3M16.2 4.5v15m-3-3 3 3 3-3' }],
] as const satisfies readonly UiIconNode[];

export const arrowUpRightIcon = [
  ['path', { d: 'M5.5 18.5 18.5 5.5M11 5.5h7.5V13' }],
] as const satisfies readonly UiIconNode[];

export const atSignIcon = [
  ['circle', { cx: '11.5', cy: '11.5', r: '3.5' }],
  ['path', { d: 'M15 8v6a2 2 0 0 0 4 0v-2.5a7.5 7.5 0 1 0-3.4 6.3' }],
] as const satisfies readonly UiIconNode[];

export const banIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M6.2 6.2 17.8 17.8' }],
] as const satisfies readonly UiIconNode[];

export const bellIcon = [
  [
    'path',
    { d: 'M8.5 18h7M6 16h12l-1.3-2.2V10a4.7 4.7 0 0 0-9.4 0v3.8L6 16ZM10 20c1 1 3 1 4 0M12 3v2.3' },
  ],
] as const satisfies readonly UiIconNode[];

export const boldIcon = [
  ['path', { d: 'M7 4.5h5a3.5 3.5 0 0 1 0 7H7M7 11.5h6a4 4 0 0 1 0 8H7v-15' }],
] as const satisfies readonly UiIconNode[];

export const bookOpenIcon = [
  [
    'path',
    {
      d: 'M12 7c-2.1-2-5.2-2.6-8.5-2v13c3.3-.6 6.4 0 8.5 2 2.1-2 5.2-2.6 8.5-2V5C17.2 4.4 14.1 5 12 7Zm0 0v13',
    },
  ],
  ['path', { d: 'M6.5 9c1-.1 1.9.1 2.8.5m5.4 0c.9-.4 1.8-.6 2.8-.5' }],
] as const satisfies readonly UiIconNode[];

export const botIcon = [
  ['rect', { x: '4', y: '7', width: '16', height: '13', rx: '4' }],
  ['path', { d: 'M12 7V3M2 12v3M22 12v3M9.5 16h5M8.5 11.5v1M15.5 11.5v1' }],
] as const satisfies readonly UiIconNode[];

export const boxesIcon = [
  ['rect', { x: '8.5', y: '3.5', width: '7', height: '7', rx: '2' }],
  ['rect', { x: '3.5', y: '13.5', width: '7', height: '7', rx: '2' }],
  ['rect', { x: '13.5', y: '13.5', width: '7', height: '7', rx: '2' }],
  ['path', { d: 'M12 3.5v2.8M7 13.5v2.8m10-2.8v2.8' }],
] as const satisfies readonly UiIconNode[];

export const brainIcon = [
  [
    'path',
    {
      d: 'M12 5.5c-2-3-6-1.8-6 1.5-3 .6-4 4-.9 6.1-1.7 3 1 6.5 4 5.8 1.1 1.6 2.9 1.3 2.9-.9V5.5ZM12 5.5c2-3 6-1.8 6 1.5 3 .6 4 4 .9 6.1 1.7 3-1 6.5-4 5.8-1.1 1.6-2.9 1.3-2.9-.9M6 7c0 2 1 3 3 3M18 7c0 2-1 3-3 3M5.1 13.1c2-1 3.4 0 3.4 2M18.9 13.1c-2-1-3.4 0-3.4 2',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const brushCleaningIcon = [
  [
    'path',
    {
      d: 'm9 12 7.5-7.5A1.8 1.8 0 0 1 19 7l-7.5 7.5M7 11l6 6-3.5 3H4.5l-1-1 3.5-8ZM6 16l3 3M17 13v4m-2-2h4',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const bugIcon = [
  ['rect', { x: '7', y: '8', width: '10', height: '12', rx: '5' }],
  [
    'path',
    { d: 'M9 8V6a3 3 0 0 1 6 0v2M7 11 4 9M17 11l3-2M7 15H3M17 15h4M8 18l-3 3M16 18l3 3M12 12v5' },
  ],
] as const satisfies readonly UiIconNode[];

export const building2Icon = [
  ['rect', { x: '4.5', y: '3.5', width: '10', height: '17', rx: '2.5' }],
  ['path', { d: 'M14.5 8.5H17a2.5 2.5 0 0 1 2.5 2.5v9.5h-5M8 7.5h3m-3 4h3m-3 9v-4h3v4' }],
] as const satisfies readonly UiIconNode[];

export const cableIcon = [
  ['path', { d: 'M5.5 3.5v3m4-3v3M7.5 11v4a4 4 0 0 0 8 0v-2' }],
  ['rect', { x: '4.5', y: '6.5', width: '6', height: '4.5', rx: '2' }],
  ['rect', { x: '12.5', y: '8.5', width: '6', height: '4.5', rx: '2' }],
  ['path', { d: 'M13.5 5.5v3m4-3v3' }],
] as const satisfies readonly UiIconNode[];

export const calendarClockIcon = [
  [
    'path',
    {
      d: 'M11.3 20.1H6.25a2.5 2.5 0 0 1-2.5-2.5V8a2.5 2.5 0 0 1 2.5-2.5h10a2.5 2.5 0 0 1 2.5 2.5v2.5M7.7 3.8v3.3m6.9-3.3v3.3M3.75 9.8h15',
    },
  ],
  ['circle', { cx: '16.4', cy: '16.4', r: '3.85' }],
  ['path', { d: 'M16.4 14.3v2.1l1.5.9' }],
] as const satisfies readonly UiIconNode[];

export const checkIcon = [
  ['path', { d: 'M5.1 12.3 9.7 16.9 18.9 7.1' }],
] as const satisfies readonly UiIconNode[];

export const checkCheckIcon = [
  ['path', { d: 'M3.8 12.4 7.2 15.8 14.8 7.8M11.7 14.1l1.6 1.7 6.9-7.4' }],
] as const satisfies readonly UiIconNode[];

export const chevronDownIcon = [
  ['path', { d: 'M6.5 9 12 14.5 17.5 9' }],
] as const satisfies readonly UiIconNode[];

export const chevronLeftIcon = [
  ['path', { d: 'M15 6.5 9.5 12l5.5 5.5' }],
] as const satisfies readonly UiIconNode[];

export const chevronRightIcon = [
  ['path', { d: 'M9 6.5 14.5 12 9 17.5' }],
] as const satisfies readonly UiIconNode[];

export const chevronUpIcon = [
  ['path', { d: 'M6.5 15 12 9.5l5.5 5.5' }],
] as const satisfies readonly UiIconNode[];

export const chevronsDownUpIcon = [
  ['path', { d: 'M8.1 5.9 12 10l3.9-4.1M8.1 18.1 12 14l3.9 4.1' }],
] as const satisfies readonly UiIconNode[];

export const chevronsUpDownIcon = [
  ['path', { d: 'M8.1 8.9 12 4.8l3.9 4.1M8.1 15.1l3.9 4.1 3.9-4.1' }],
] as const satisfies readonly UiIconNode[];

export const circleIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
] as const satisfies readonly UiIconNode[];

export const circleAlertIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M12 7.9v5.2M12 16.2h.01' }],
] as const satisfies readonly UiIconNode[];

export const circleCheckIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M8.1 12.1 10.7 14.7 15.9 9.3' }],
] as const satisfies readonly UiIconNode[];

export const circleDashedIcon = [
  ['path', { d: 'M20.25 12A8.25 8.25 0 0 1 19.477 15.487' }],
  ['path', { d: 'M17.834 17.834A8.25 8.25 0 0 1 14.822 19.752' }],
  ['path', { d: 'M12 20.25A8.25 8.25 0 0 1 8.513 19.477' }],
  ['path', { d: 'M6.166 17.834A8.25 8.25 0 0 1 4.248 14.822' }],
  ['path', { d: 'M3.75 12A8.25 8.25 0 0 1 4.523 8.513' }],
  ['path', { d: 'M6.166 6.166A8.25 8.25 0 0 1 9.178 4.248' }],
  ['path', { d: 'M12 3.75A8.25 8.25 0 0 1 15.487 4.523' }],
  ['path', { d: 'M17.834 6.166A8.25 8.25 0 0 1 19.752 9.178' }],
] as const satisfies readonly UiIconNode[];

export const circleDotIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['circle', { cx: '12', cy: '12', r: '2.1' }],
] as const satisfies readonly UiIconNode[];

export const circleMinusIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M8.2 12h7.6' }],
] as const satisfies readonly UiIconNode[];

export const circleQuestionMarkIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  [
    'path',
    {
      d: 'M9.9 9.5c0-1.3.9-2.2 2.2-2.2s2.3.9 2.3 2.2c0 1.1-.6 1.7-1.6 2.3-.6.4-.9.8-.9 1.6M12 16.3h.01',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const circleSlashIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M8.5 15.5 15.5 8.5' }],
] as const satisfies readonly UiIconNode[];

export const circleSlash2Icon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M6.2 17.8 17.8 6.2' }],
] as const satisfies readonly UiIconNode[];

export const circleStopIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['rect', { x: '9', y: '9', width: '6', height: '6', rx: '1.2' }],
] as const satisfies readonly UiIconNode[];

export const circleXIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M9 9l6 6m0-6-6 6' }],
] as const satisfies readonly UiIconNode[];

export const clipboardListIcon = [
  [
    'path',
    {
      d: 'M9 5.5H7.5A2 2 0 0 0 5.5 7.5V18a2.5 2.5 0 0 0 2.5 2.5h8a2.5 2.5 0 0 0 2.5-2.5V7.5a2 2 0 0 0-2-2H15',
    },
  ],
  ['rect', { x: '9', y: '3.5', width: '6', height: '4', rx: '2' }],
  ['path', { d: 'M11.5 12h3.5m-3.5 4h3.5' }],
  ['circle', { cx: '8.5', cy: '12', r: '0.35' }],
  ['circle', { cx: '8.5', cy: '16', r: '0.35' }],
] as const satisfies readonly UiIconNode[];

export const clipboardPasteIcon = [
  [
    'path',
    {
      d: 'M9 5.5H7.5A2 2 0 0 0 5.5 7.5V18a2.5 2.5 0 0 0 2.5 2.5h8a2.5 2.5 0 0 0 2.5-2.5V7.5a2 2 0 0 0-2-2H15',
    },
  ],
  ['rect', { x: '9', y: '3.5', width: '6', height: '4', rx: '2' }],
  ['path', { d: 'M8.5 14h7m-3-3 3 3-3 3' }],
] as const satisfies readonly UiIconNode[];

export const clockIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M12 7.1V12l3.8 2.1' }],
] as const satisfies readonly UiIconNode[];

export const clock3Icon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M12 7.1V12h4.1' }],
] as const satisfies readonly UiIconNode[];

export const cloudIcon = [
  ['path', { d: 'M6.5 18H18a4 4 0 0 0 .5-8 6 6 0 0 0-11.4-2A5 5 0 0 0 6.5 18Z' }],
] as const satisfies readonly UiIconNode[];

export const cloudOffIcon = [
  ['path', { d: 'M20 17a4 4 0 0 0-1.5-7A6 6 0 0 0 9 6M6 8.1A5 5 0 0 0 6.5 18H16M3 3l18 18' }],
] as const satisfies readonly UiIconNode[];

export const codeIcon = [
  ['path', { d: 'm8 6-5.5 6L8 18M16 6l5.5 6-5.5 6M13 4l-2 16' }],
] as const satisfies readonly UiIconNode[];

export const columns2Icon = [
  ['rect', { x: '3.5', y: '4', width: '17', height: '16', rx: '3' }],
  ['path', { d: 'M12 4v16' }],
] as const satisfies readonly UiIconNode[];

export const commandIcon = [
  [
    'path',
    {
      d: 'M8 8H5.5A2.5 2.5 0 1 1 8 5.5v13a2.5 2.5 0 1 1-2.5-2.5h13a2.5 2.5 0 1 1-2.5 2.5v-13A2.5 2.5 0 1 1 18.5 8H8',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const compassIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'm15.8 8.2-2.2 5.4-5.4 2.2 2.2-5.4Zm-5.4 2.2 3.2 3.2' }],
] as const satisfies readonly UiIconNode[];

export const copyIcon = [
  ['rect', { x: '8', y: '8', width: '12.5', height: '13', rx: '2.5' }],
  ['path', { d: 'M5 16H4a1 1 0 0 1-1-1V5a2 2 0 0 1 2-2h10a1 1 0 0 1 1 1v1' }],
] as const satisfies readonly UiIconNode[];

export const cornerLeftUpIcon = [
  ['path', { d: 'M18.5 19H11a4 4 0 0 1-4-4V4M3.5 8 7 4l3.5 4' }],
] as const satisfies readonly UiIconNode[];

export const cpuIcon = [
  ['rect', { x: '6.5', y: '6.5', width: '11', height: '11', rx: '2.5' }],
  ['rect', { x: '10', y: '10', width: '4', height: '4', rx: '1' }],
  ['path', { d: 'M9.5 3.5v3m5-3v3m-5 11v3m5-3v3m-11-11h3m-3 5h3m11-5h3m-3 5h3' }],
] as const satisfies readonly UiIconNode[];

export const cropIcon = [
  ['path', { d: 'M7 3.5v12a1.5 1.5 0 0 0 1.5 1.5h12M3.5 7h12a1.5 1.5 0 0 1 1.5 1.5v12' }],
] as const satisfies readonly UiIconNode[];

export const downloadIcon = [
  ['path', { d: 'M4.5 15.5v2a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2v-2M12 4.5v10m-4-4 4 4 4-4' }],
] as const satisfies readonly UiIconNode[];

export const earthIcon = [
  ['circle', { cx: '12', cy: '12', r: '9' }],
  ['path', { d: 'm6 5 1 4 4 1 1 3-3 1-1 4M15 3.5l-1 4 3 2h3.5M20 16l-4-1-2 2v3.5' }],
] as const satisfies readonly UiIconNode[];

export const ellipseIcon = [
  ['ellipse', { cx: '12', cy: '12', rx: '8', ry: '6' }],
] as const satisfies readonly UiIconNode[];

export const ellipsisIcon = [
  ['circle', { cx: '5', cy: '12', r: '0.8' }],
  ['circle', { cx: '12', cy: '12', r: '0.8' }],
  ['circle', { cx: '19', cy: '12', r: '0.8' }],
] as const satisfies readonly UiIconNode[];

export const externalLinkIcon = [
  [
    'path',
    { d: 'M10 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4M13.5 3.5h7v7M20 4 11 13' },
  ],
] as const satisfies readonly UiIconNode[];

export const eyeIcon = [
  [
    'path',
    {
      d: 'M3.8 12C5.5 8.7 8.2 6.5 12 6.5s6.5 2.2 8.2 5.5c-1.7 3.3-4.4 5.5-8.2 5.5S5.5 15.3 3.8 12Z',
    },
  ],
  ['circle', { cx: '12', cy: '12', r: '2.25' }],
] as const satisfies readonly UiIconNode[];

export const eyeClosedIcon = [
  [
    'path',
    { d: 'M4 9.2c1.8 3.5 4.5 5.4 8 5.4s6.2-1.9 8-5.4M7.1 13.7l-1.4 2.8M12 14.6v3.1m4.9-4 1.4 2.8' },
  ],
] as const satisfies readonly UiIconNode[];

export const eyeOffIcon = [
  [
    'path',
    {
      d: 'm4.2 4.2 15.6 15.6M10.3 6.7C14.8 5.7 18.4 8.6 20.2 12c-.6 1.1-1.3 2.1-2.2 3M5.7 8.2c-.8.8-1.4 1.9-1.9 3.8 1.7 3.3 4.4 5.5 8.2 5.5 1.3 0 2.5-.3 3.6-.9M10 10.9a2.25 2.25 0 0 0 3.1 3.1',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const fileIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
] as const satisfies readonly UiIconNode[];

export const fileArchiveIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M12 11v4m-1.5-3h3m-3 2h3' }],
  ['rect', { x: '10.5', y: '16', width: '3', height: '2', rx: '1' }],
] as const satisfies readonly UiIconNode[];

export const fileAudioIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M11 16.5v-5l4-1v3' }],
  ['circle', { cx: '9.5', cy: '16.5', r: '1.5' }],
] as const satisfies readonly UiIconNode[];

export const fileCodeIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'm9.5 12-2 2.5 2 2.5m5-5 2 2.5-2 2.5' }],
] as const satisfies readonly UiIconNode[];

export const fileCode2Icon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'm9 12.5-1.5 2L9 16m6-3.5 1.5 2L15 16m-2-4-2 5' }],
] as const satisfies readonly UiIconNode[];

export const fileDiffIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M9 12h6m-3-2v4m-3 3h6' }],
] as const satisfies readonly UiIconNode[];

export const fileImageIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'm8 17 3-3 2.5 2 2-2 1 1' }],
  ['circle', { cx: '9', cy: '11.5', r: '0.75' }],
] as const satisfies readonly UiIconNode[];

export const fileJsonIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  [
    'path',
    { d: 'M10 11.5H9v2c0 .7-.4 1-1 1 .6 0 1 .3 1 1v2h1m4-6h1v2c0 .7.4 1 1 1-.6 0-1 .3-1 1v2h-1' },
  ],
] as const satisfies readonly UiIconNode[];

export const fileSpreadsheetIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['rect', { x: '8.5', y: '11.5', width: '7', height: '6', rx: '1' }],
  ['path', { d: 'M12 11.5v6m-3.5-3h7' }],
] as const satisfies readonly UiIconNode[];

export const fileTextIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M8.5 12.5h7m-7 4h5' }],
] as const satisfies readonly UiIconNode[];

export const fileVideoIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'm10 11.5 5 3-5 3v-6Z' }],
] as const satisfies readonly UiIconNode[];

export const fileWarningIcon = [
  [
    'path',
    {
      d: 'M13.5 3.5H8A2.5 2.5 0 0 0 5.5 6v12A2.5 2.5 0 0 0 8 20.5h8a2.5 2.5 0 0 0 2.5-2.5V8.5L13.5 3.5Z',
    },
  ],
  ['path', { d: 'M13.5 3.5v3a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M12 11.5v3.3' }],
  ['circle', { cx: '12', cy: '17', r: '0.4' }],
] as const satisfies readonly UiIconNode[];

export const filesIcon = [
  ['path', { d: 'M6 7.5H5A2 2 0 0 0 3 9.5V18a2.5 2.5 0 0 0 2.5 2.5H14' }],
  [
    'path',
    {
      d: 'M15.5 3.5H11A2.5 2.5 0 0 0 8.5 6v9A2.5 2.5 0 0 0 11 17.5h6.5A2.5 2.5 0 0 0 20 15V8l-4.5-4.5Z',
    },
  ],
  ['path', { d: 'M15.5 3.5V6A2 2 0 0 0 17.5 8H20' }],
] as const satisfies readonly UiIconNode[];

export const flaskConicalIcon = [
  ['path', { d: 'M9 3h6M10 3v6l-5.5 9a2 2 0 0 0 1.7 3h11.6a2 2 0 0 0 1.7-3L14 9V3M8 14h8M9 17h2' }],
] as const satisfies readonly UiIconNode[];

export const folderIcon = [
  [
    'path',
    {
      d: 'M3.5 8V6.5a2 2 0 0 1 2-2h3.2c.6 0 1.1.3 1.5.7l1.6 1.8h6.7a2 2 0 0 1 2 2V17a2.5 2.5 0 0 1-2.5 2.5H6A2.5 2.5 0 0 1 3.5 17V8Z',
    },
  ],
  ['line', { x1: '3.5', y1: '9', x2: '20.5', y2: '9' }],
] as const satisfies readonly UiIconNode[];

export const folderGit2Icon = [
  [
    'path',
    {
      d: 'M3.5 8V6.5a2 2 0 0 1 2-2h3.2c.6 0 1.1.3 1.5.7l1.6 1.8h6.7a2 2 0 0 1 2 2V17a2.5 2.5 0 0 1-2.5 2.5H6A2.5 2.5 0 0 1 3.5 17V8Z',
    },
  ],
  ['circle', { cx: '8', cy: '11.5', r: '1.25' }],
  ['circle', { cx: '8', cy: '17', r: '1.25' }],
  ['circle', { cx: '15.5', cy: '11.5', r: '1.25' }],
  ['path', { d: 'M8 12.75v3m0-.75h4.5a3 3 0 0 0 3-3v-.25' }],
] as const satisfies readonly UiIconNode[];

export const folderOpenIcon = [
  ['path', { d: 'M3.5 11V6.5a2 2 0 0 1 2-2h3.2c.6 0 1.1.3 1.5.7l1.6 1.8h6.7a2 2 0 0 1 2 2' }],
  ['path', { d: 'M3.5 11h17l-1.4 6.5a2.5 2.5 0 0 1-2.4 2H7.3a2.5 2.5 0 0 1-2.4-2L3.5 11Z' }],
] as const satisfies readonly UiIconNode[];

export const folderPlusIcon = [
  [
    'path',
    {
      d: 'M3.5 8V6.5a2 2 0 0 1 2-2h3.2c.6 0 1.1.3 1.5.7l1.6 1.8h6.7a2 2 0 0 1 2 2V17a2.5 2.5 0 0 1-2.5 2.5H6A2.5 2.5 0 0 1 3.5 17V8Z',
    },
  ],
  ['path', { d: 'M12 10.5v6m-3-3h6' }],
] as const satisfies readonly UiIconNode[];

export const folderTreeIcon = [
  ['path', { d: 'M3.5 10.5v7a1.5 1.5 0 0 0 1.5 1.5h4m-5.5-6H9' }],
  ['path', { d: 'M3.5 7.5V5a1.5 1.5 0 0 1 1.5-1.5h2l1.5 1.5H12v4H5a1.5 1.5 0 0 1-1.5-1.5Z' }],
  ['rect', { x: '9', y: '11', width: '11.5', height: '4', rx: '1.5' }],
  ['rect', { x: '9', y: '17', width: '11.5', height: '4', rx: '1.5' }],
] as const satisfies readonly UiIconNode[];

export const funnelIcon = [
  ['path', { d: 'M4 4h16v2l-6.5 7v6l-3 1v-7L4 6V4Z' }],
] as const satisfies readonly UiIconNode[];

export const gaugeIcon = [
  [
    'path',
    {
      d: 'M4.8 18.3c-1.6-3.2-.9-7.2 1.6-9.8 3.1-3.1 8.1-3.1 11.2 0 2.5 2.6 3.2 6.6 1.6 9.8ZM7.3 10.1l1.2 1.2M12 7.3v1.8m.8 4.3 3.4-3.4',
    },
  ],
  ['circle', { cx: '12', cy: '14.2', r: '1.1' }],
] as const satisfies readonly UiIconNode[];

export const gitBranchIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '6.5', r: '2' }],
  ['path', { d: 'M7 14c0-4.5 10-1 10-5.5' }],
] as const satisfies readonly UiIconNode[];

export const gitBranchPlusIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '5.5', r: '2' }],
  ['path', { d: 'M7 13.5c0-4 10-1.5 10-6m0 7v6m-3-3h6' }],
] as const satisfies readonly UiIconNode[];

export const gitForkIcon = [
  ['circle', { cx: '6.5', cy: '5.5', r: '2' }],
  ['circle', { cx: '17.5', cy: '5.5', r: '2' }],
  ['circle', { cx: '12', cy: '18.5', r: '2' }],
  ['path', { d: 'M6.5 7.5v1C6.5 13 12 10.5 12 15v1.5m5.5-9v1C17.5 13 12 10.5 12 15' }],
] as const satisfies readonly UiIconNode[];

export const gitMergeIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '5.5', r: '2' }],
  ['path', { d: 'M17 7.5v1C17 14 7 10.5 7 15' }],
] as const satisfies readonly UiIconNode[];

export const gitPullRequestIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '18.5', r: '2' }],
  ['path', { d: 'M17 16.5v-6a4 4 0 0 0-4-4h-1m2.5-2.5L12 6.5 14.5 9' }],
] as const satisfies readonly UiIconNode[];

export const gitPullRequestArrowIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '18.5', r: '2' }],
  ['path', { d: 'M17 16.5v-3m-4-7h7m-3-3 3 3-3 3' }],
] as const satisfies readonly UiIconNode[];

export const gitPullRequestClosedIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '18.5', r: '2' }],
  ['path', { d: 'M17 16.5V12m-2.5-8 5 5m0-5-5 5' }],
] as const satisfies readonly UiIconNode[];

export const gitPullRequestDraftIcon = [
  ['circle', { cx: '7', cy: '5.5', r: '2' }],
  ['circle', { cx: '7', cy: '18.5', r: '2' }],
  ['line', { x1: '7', y1: '7.5', x2: '7', y2: '16.5' }],
  ['circle', { cx: '17', cy: '18.5', r: '2' }],
  ['path', { d: 'M17 16.5v-2m0-3v-1m-1-3a4 4 0 0 0-3-1' }],
] as const satisfies readonly UiIconNode[];

export const globeIcon = [
  ['circle', { cx: '12', cy: '12', r: '9' }],
  ['path', { d: 'M3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z' }],
] as const satisfies readonly UiIconNode[];

export const gripHorizontalIcon = [
  ['circle', { cx: '6', cy: '9', r: '0.6' }],
  ['circle', { cx: '12', cy: '9', r: '0.6' }],
  ['circle', { cx: '18', cy: '9', r: '0.6' }],
  ['circle', { cx: '6', cy: '15', r: '0.6' }],
  ['circle', { cx: '12', cy: '15', r: '0.6' }],
  ['circle', { cx: '18', cy: '15', r: '0.6' }],
] as const satisfies readonly UiIconNode[];

export const gripVerticalIcon = [
  ['circle', { cx: '9', cy: '6', r: '0.6' }],
  ['circle', { cx: '15', cy: '6', r: '0.6' }],
  ['circle', { cx: '9', cy: '12', r: '0.6' }],
  ['circle', { cx: '15', cy: '12', r: '0.6' }],
  ['circle', { cx: '9', cy: '18', r: '0.6' }],
  ['circle', { cx: '15', cy: '18', r: '0.6' }],
] as const satisfies readonly UiIconNode[];

export const handIcon = [
  [
    'path',
    {
      d: 'M7.5 11V7a1.5 1.5 0 0 1 3 0v4M10.5 9V5.5a1.5 1.5 0 0 1 3 0V11M13.5 8a1.5 1.5 0 0 1 3 0v4M16.5 10a1.5 1.5 0 0 1 3 0v4.5a6 6 0 0 1-6 6h-1.2a5 5 0 0 1-3.9-1.9l-4.5-5.7a1.6 1.6 0 0 1 2.3-2.2L7.5 12',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const hardDriveIcon = [
  [
    'path',
    {
      d: 'm5.5 5.5-2 9v3a3 3 0 0 0 3 3h11a3 3 0 0 0 3-3v-3l-2-9a2 2 0 0 0-2-1.5h-9a2 2 0 0 0-2 1.5Z',
    },
  ],
  ['line', { x1: '3.5', y1: '14.5', x2: '20.5', y2: '14.5' }],
  ['line', { x1: '7', y1: '17.5', x2: '10', y2: '17.5' }],
  ['circle', { cx: '17', cy: '17.5', r: '0.4' }],
] as const satisfies readonly UiIconNode[];

export const highlighterIcon = [
  ['path', { d: 'm8 13.5 7-9 5 4-7 9-5-4ZM8 13.5l-3 3.7 3.5 2 3-3M4 20h7' }],
] as const satisfies readonly UiIconNode[];

export const historyIcon = [
  ['path', { d: 'M5.3 7a8 8 0 1 1-1.1 8M4.5 3.8v4h4M12 7.5V12l3.5 2' }],
] as const satisfies readonly UiIconNode[];

export const houseIcon = [
  [
    'path',
    {
      d: 'm3.5 10 7.2-6a2 2 0 0 1 2.6 0l7.2 6M5.5 8.5V18a2 2 0 0 0 2 2h3v-6h3v6h3a2 2 0 0 0 2-2V8.5',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const imageIcon = [
  ['rect', { x: '4', y: '5', width: '16', height: '14', rx: '2.5' }],
  ['circle', { cx: '8.5', cy: '9.3', r: '1.2' }],
  ['path', { d: 'm4.5 16 4-3.5 4 3 3-2.5 4 3.5' }],
] as const satisfies readonly UiIconNode[];

export const imageOffIcon = [
  [
    'path',
    {
      d: 'M10 5h7.5A2.5 2.5 0 0 1 20 7.5V14M4 10v6.5A2.5 2.5 0 0 0 6.5 19H14M4.5 16l4-3.5 2 1.5M4 4l16 16',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const imagePlusIcon = [
  [
    'path',
    { d: 'M13 5H6.5A2.5 2.5 0 0 0 4 7.5v9A2.5 2.5 0 0 0 6.5 19h11a2.5 2.5 0 0 0 2.5-2.5V12' },
  ],
  ['circle', { cx: '8.5', cy: '9.3', r: '1.2' }],
  ['path', { d: 'm4.5 16 4-3.5 4 3 3-2.5 4 3.5M18 3.5v6m-3-3h6' }],
] as const satisfies readonly UiIconNode[];

export const infoIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.5' }],
  ['path', { d: 'M11 11h1.5v6M10.5 17h4M12 7v.2' }],
] as const satisfies readonly UiIconNode[];

export const italicIcon = [
  ['path', { d: 'M10 4.5h8M6 19.5h8M14.5 4.5l-5 15' }],
] as const satisfies readonly UiIconNode[];

export const keyRoundIcon = [
  ['circle', { cx: '8.6', cy: '8.9', r: '4.65' }],
  ['path', { d: 'm11.9 12.2 7.9 7.9M16 16.3l2-2m0 4 2-2' }],
] as const satisfies readonly UiIconNode[];

export const keyboardIcon = [
  ['rect', { x: '3.5', y: '6', width: '17', height: '12', rx: '2.5' }],
  ['path', { d: 'M7 9.5h1m3.5 0h1m3.5 0h1m-10 4h1m3.5 0h1m3.5 0h1M9 16h6' }],
] as const satisfies readonly UiIconNode[];

export const laptopIcon = [
  ['rect', { x: '5.5', y: '4.5', width: '13', height: '12', rx: '2' }],
  ['path', { d: 'M5.5 16.5h-2v1a3 3 0 0 0 3 3h11a3 3 0 0 0 3-3v-1h-2m-9 0h5' }],
] as const satisfies readonly UiIconNode[];

export const layersIcon = [
  ['path', { d: 'm3 8 9-5 9 5-9 5-9-5ZM3 12.5l9 5 9-5M3 17l9 5 9-5' }],
] as const satisfies readonly UiIconNode[];

export const layoutGridIcon = [
  ['rect', { x: '3.5', y: '3.5', width: '6.5', height: '6.5', rx: '1.8' }],
  ['rect', { x: '14', y: '3.5', width: '6.5', height: '6.5', rx: '1.8' }],
  ['rect', { x: '3.5', y: '14', width: '6.5', height: '6.5', rx: '1.8' }],
  ['rect', { x: '14', y: '14', width: '6.5', height: '6.5', rx: '1.8' }],
] as const satisfies readonly UiIconNode[];

export const lineIcon = [['path', { d: 'm5 18.5 14-13' }]] as const satisfies readonly UiIconNode[];

export const linkIcon = [
  ['path', { d: 'm8.5 13.5 7-3M9.5 8 7 9a4 4 0 1 0 3 7.5l2-1M14.5 16l2.5-1a4 4 0 0 0-3-7.5l-2 1' }],
] as const satisfies readonly UiIconNode[];

export const link2Icon = [
  ['path', { d: 'm8 16 8-8M9 7l2.5-2.5a5 5 0 0 1 7 7L16 14M8 10l-2.5 2.5a5 5 0 0 0 7 7L15 17' }],
] as const satisfies readonly UiIconNode[];

export const listIcon = [
  ['path', { d: 'M8 5h12M8 12h12M8 19h12M3.5 5h.5M3.5 12h.5M3.5 19h.5' }],
] as const satisfies readonly UiIconNode[];

export const listChecksIcon = [
  [
    'path',
    { d: 'm3 5 1.5 1.5L7 3.5M10 5h10M3 12l1.5 1.5L7 10.5M10 12h10M3 19l1.5 1.5L7 17.5M10 19h10' },
  ],
] as const satisfies readonly UiIconNode[];

export const listFilterIcon = [
  ['path', { d: 'M3.5 5.5h17M6.5 12h11M9.5 18.5h5' }],
] as const satisfies readonly UiIconNode[];

export const listTodoIcon = [
  ['rect', { x: '3', y: '3.5', width: '5', height: '5', rx: '1.2' }],
  ['rect', { x: '3', y: '15.5', width: '5', height: '5', rx: '1.2' }],
  ['path', { d: 'M12 6h9M12 18h9' }],
] as const satisfies readonly UiIconNode[];

export const loaderIcon = [
  ['path', { d: 'M12 6.1 12 3.75' }],
  ['path', { d: 'M16.172 7.828 17.834 6.166' }],
  ['path', { d: 'M17.9 12 20.25 12' }],
  ['path', { d: 'M16.172 16.172 17.834 17.834' }],
  ['path', { d: 'M12 17.9 12 20.25' }],
  ['path', { d: 'M7.828 16.172 6.166 17.834' }],
  ['path', { d: 'M6.1 12 3.75 12' }],
] as const satisfies readonly UiIconNode[];

export const loaderCircleIcon = [
  ['path', { d: 'M20.25 12A8.25 8.25 0 1 1 12 3.75' }],
] as const satisfies readonly UiIconNode[];

export const lockIcon = [
  ['rect', { x: '5.2', y: '10.2', width: '13.6', height: '10', rx: '2.5' }],
  ['path', { d: 'M8.1 10.2V7.7a3.9 3.9 0 0 1 7.8 0v2.5' }],
] as const satisfies readonly UiIconNode[];

export const lockKeyholeIcon = [
  ['rect', { x: '5.2', y: '10.2', width: '13.6', height: '10', rx: '2.5' }],
  ['path', { d: 'M8.1 10.2V7.7a3.9 3.9 0 0 1 7.8 0v2.5M12 15.3v1.6' }],
  ['circle', { cx: '12', cy: '14.25', r: '1.05' }],
] as const satisfies readonly UiIconNode[];

export const logInIcon = [
  ['path', { d: 'M13 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5M3 12h12M11 8l4 4-4 4' }],
] as const satisfies readonly UiIconNode[];

export const logOutIcon = [
  ['path', { d: 'M10 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h4M10 12h11M17 8l4 4-4 4' }],
] as const satisfies readonly UiIconNode[];

export const mailIcon = [
  ['rect', { x: '3', y: '5', width: '18', height: '14', rx: '3' }],
  ['path', { d: 'm4 7 7 5a1.7 1.7 0 0 0 2 0l7-5' }],
] as const satisfies readonly UiIconNode[];

export const maximizeIcon = [
  ['path', { d: 'M4.5 9V4.5H9M15 4.5h4.5V9M19.5 15v4.5H15M9 19.5H4.5V15' }],
] as const satisfies readonly UiIconNode[];

export const maximize2Icon = [
  ['path', { d: 'M13.5 4.5h6v6M19.5 4.5 13 11M4.5 13.5v6h6M4.5 19.5 11 13' }],
] as const satisfies readonly UiIconNode[];

export const messageCircleIcon = [
  ['path', { d: 'M12 3.5a8.5 8.5 0 1 1-4 16l-4.5 1 1-4a8.5 8.5 0 0 1 7.5-13ZM8 10h8M8 14h5' }],
] as const satisfies readonly UiIconNode[];

export const messageSquareIcon = [
  [
    'path',
    {
      d: 'M7 4h10a3.5 3.5 0 0 1 3.5 3.5v7A3.5 3.5 0 0 1 17 18h-6l-5.5 3v-3.3a3.5 3.5 0 0 1-2-3.2v-7A3.5 3.5 0 0 1 7 4Z',
    },
  ],
  ['path', { d: 'M8 9h8M8 13h5' }],
] as const satisfies readonly UiIconNode[];

export const messageSquareMoreIcon = [
  [
    'path',
    {
      d: 'M7 4h10a3.5 3.5 0 0 1 3.5 3.5v7A3.5 3.5 0 0 1 17 18h-6l-5.5 3v-3.3a3.5 3.5 0 0 1-2-3.2v-7A3.5 3.5 0 0 1 7 4Z',
    },
  ],
  ['circle', { cx: '7.5', cy: '11', r: '0.5' }],
  ['circle', { cx: '12', cy: '11', r: '0.5' }],
  ['circle', { cx: '16.5', cy: '11', r: '0.5' }],
] as const satisfies readonly UiIconNode[];

export const messageSquareOffIcon = [
  [
    'path',
    { d: 'M8 4h9a3.5 3.5 0 0 1 3.5 3.5v7M16 18h-5l-5.5 3v-3.3a3.5 3.5 0 0 1-2-3.2v-7M3 3l18 18' },
  ],
] as const satisfies readonly UiIconNode[];

export const messageSquarePlusIcon = [
  [
    'path',
    {
      d: 'M7 4h10a3.5 3.5 0 0 1 3.5 3.5v7A3.5 3.5 0 0 1 17 18h-6l-5.5 3v-3.3a3.5 3.5 0 0 1-2-3.2v-7A3.5 3.5 0 0 1 7 4Z',
    },
  ],
  ['path', { d: 'M8 11h8M12 7v8' }],
] as const satisfies readonly UiIconNode[];

export const messagesSquareIcon = [
  ['path', { d: 'M8 15H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v1' }],
  [
    'path',
    { d: 'M12 9h6a3 3 0 0 1 3 3v5a3 3 0 0 1-2 2.8V22l-4-2h-3a3 3 0 0 1-3-3v-5a3 3 0 0 1 3-3Z' },
  ],
] as const satisfies readonly UiIconNode[];

export const minimize2Icon = [
  ['path', { d: 'm19.5 4.5-6 6M13.5 5.5v5h5M4.5 19.5l6-6M5.5 13.5h5v5' }],
] as const satisfies readonly UiIconNode[];

export const minusIcon = [['path', { d: 'M5.5 12h13' }]] as const satisfies readonly UiIconNode[];

export const monitorIcon = [
  ['rect', { x: '3.5', y: '4.5', width: '17', height: '12', rx: '2.5' }],
  ['path', { d: 'M12 16.5v4m-4 0h8' }],
] as const satisfies readonly UiIconNode[];

export const monitorPlayIcon = [
  ['rect', { x: '3.5', y: '4.5', width: '17', height: '12', rx: '2.5' }],
  ['path', { d: 'M12 16.5v4m-4 0h8' }],
  ['path', { d: 'm10 8 5 2.5-5 2.5V8Z' }],
] as const satisfies readonly UiIconNode[];

export const monitorSmartphoneIcon = [
  [
    'path',
    {
      d: 'M11.5 16.5H6A2.5 2.5 0 0 1 3.5 14V7A2.5 2.5 0 0 1 6 4.5h11A2.5 2.5 0 0 1 19.5 7v1.5M9 16.5v4m-3 0h6',
    },
  ],
  ['rect', { x: '14.5', y: '10.5', width: '6', height: '10', rx: '1.5' }],
  ['line', { x1: '17', y1: '17.5', x2: '18', y2: '17.5' }],
] as const satisfies readonly UiIconNode[];

export const moonIcon = [
  ['path', { d: 'M19.8 14.5A8.5 8.5 0 0 1 9.5 4.2a8.5 8.5 0 1 0 10.3 10.3Z' }],
] as const satisfies readonly UiIconNode[];

export const mousePointer2Icon = [
  ['path', { d: 'M5 4.5 19.5 10.5 13 13 10.5 19.5 5 4.5Z' }],
] as const satisfies readonly UiIconNode[];

export const moveRightIcon = [
  ['path', { d: 'M4.5 9v6M7 12h12.5M15 7.5l4.5 4.5-4.5 4.5' }],
] as const satisfies readonly UiIconNode[];

export const packageOpenIcon = [
  ['path', { d: 'm6 10.5 6 3 6-3M6 13v4.5l6 3 6-3V13m-6 .5v7' }],
  ['path', { d: 'm6 10.5-3-4 6-3 3 4-6 3Zm6-3 3-4 6 3-3 4-6-3Z' }],
] as const satisfies readonly UiIconNode[];

export const paletteIcon = [
  [
    'path',
    {
      d: 'M12 4.5c-4.4 0-8 3.3-8 7.5s3.4 7.5 7.5 7.5H13a2 2 0 0 0 1-3.7c-.9-.5-.7-1.8.4-2l2.6-.3a3.3 3.3 0 0 0 3-3.3c0-3.2-3.6-5.7-8-5.7Z',
    },
  ],
  ['circle', { cx: '8', cy: '9', r: '.8' }],
  ['circle', { cx: '12', cy: '7.5', r: '.8' }],
  ['circle', { cx: '16', cy: '9', r: '.8' }],
  ['circle', { cx: '7', cy: '13', r: '.8' }],
] as const satisfies readonly UiIconNode[];

export const panelBottomIcon = [
  ['rect', { x: '3.5', y: '4', width: '17', height: '16', rx: '3' }],
  ['path', { d: 'M3.5 14h17' }],
] as const satisfies readonly UiIconNode[];

export const panelLeftIcon = [
  ['rect', { x: '3.5', y: '4', width: '17', height: '16', rx: '3' }],
  ['path', { d: 'M9.5 4v16' }],
] as const satisfies readonly UiIconNode[];

export const panelRightIcon = [
  ['rect', { x: '3.5', y: '4', width: '17', height: '16', rx: '3' }],
  ['path', { d: 'M14.5 4v16' }],
] as const satisfies readonly UiIconNode[];

export const paperclipIcon = [
  [
    'path',
    {
      d: 'm8 12 6.5-6.5a4 4 0 0 1 5.7 5.7L12 19.4a5.7 5.7 0 0 1-8-8l8.5-8.5M8 12l-1 1a2.3 2.3 0 0 0 3.3 3.3l7.2-7.2',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const pauseIcon = [
  ['rect', { x: '6', y: '4', width: '3', height: '16', rx: '1' }],
  ['rect', { x: '15', y: '4', width: '3', height: '16', rx: '1' }],
] as const satisfies readonly UiIconNode[];

export const penLineIcon = [
  ['path', { d: 'm5 18.5 1.5-7.2L14 4l6 6-7.3 7.5L5 18.5ZM5 18.5l5.7-5.7M15 20h5' }],
  ['circle', { cx: '12', cy: '11.5', r: '1.5' }],
] as const satisfies readonly UiIconNode[];

export const pencilIcon = [
  [
    'path',
    {
      d: 'm5 14.5 10-10a1.8 1.8 0 0 1 2.5 0l2 2a1.8 1.8 0 0 1 0 2.5l-10 10-5 1 1-5ZM13.5 6l4.5 4.5M5 14.5 9.5 19',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const pencilLineIcon = [
  [
    'path',
    {
      d: 'm4.5 14 9.5-9.5a1.8 1.8 0 0 1 2.5 0L19 7a1.8 1.8 0 0 1 0 2.5L9.5 19l-5 1v-6ZM12.5 6l5 5M4.5 14l5 5M14 20h6',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const pinIcon = [
  ['path', { d: 'M8 4h8M9 4v6l-3 4v2h12v-2l-3-4V4M12 16v6' }],
] as const satisfies readonly UiIconNode[];

export const pinOffIcon = [
  ['path', { d: 'M8 4h8M15 4v6l2 2M9 9v1l-3 4v2h10M12 16v6M3 3l18 18' }],
] as const satisfies readonly UiIconNode[];

export const playIcon = [
  ['path', { d: 'M7 4.8c0-.7.6-1 1.2-.6l12 7c.6.3.6 1.3 0 1.6l-12 7c-.6.4-1.2.1-1.2-.6V4.8Z' }],
] as const satisfies readonly UiIconNode[];

export const plugIcon = [
  ['path', { d: 'M8 3.5v4m8-4v4M6 7.5h12v3a6 6 0 0 1-12 0v-3Zm6 9v4' }],
] as const satisfies readonly UiIconNode[];

export const plusIcon = [
  ['path', { d: 'M5.5 12h13M12 5.5v13' }],
] as const satisfies readonly UiIconNode[];

export const priorityHighIcon = [
  ['rect', { x: '4.1', y: '14.5', width: '3.3', height: '5.2', rx: '1.2' }],
  ['rect', { x: '10.35', y: '10.25', width: '3.3', height: '9.45', rx: '1.2' }],
  ['rect', { x: '16.6', y: '5', width: '3.3', height: '14.7', rx: '1.2' }],
] as const satisfies readonly UiIconNode[];

export const priorityLowIcon = [
  ['rect', { x: '4.1', y: '14.5', width: '3.3', height: '5.2', rx: '1.2' }],
  ['rect', { x: '10.35', y: '10.25', width: '3.3', height: '9.45', rx: '1.2', opacity: '.28' }],
  ['rect', { x: '16.6', y: '5', width: '3.3', height: '14.7', rx: '1.2', opacity: '.28' }],
] as const satisfies readonly UiIconNode[];

export const priorityMediumIcon = [
  ['rect', { x: '4.1', y: '14.5', width: '3.3', height: '5.2', rx: '1.2' }],
  ['rect', { x: '10.35', y: '10.25', width: '3.3', height: '9.45', rx: '1.2' }],
  ['rect', { x: '16.6', y: '5', width: '3.3', height: '14.7', rx: '1.2', opacity: '.28' }],
] as const satisfies readonly UiIconNode[];

export const priorityNoneIcon = [
  ['rect', { x: '4.1', y: '14.5', width: '3.3', height: '5.2', rx: '1.2', opacity: '.45' }],
  ['rect', { x: '10.35', y: '10.25', width: '3.3', height: '9.45', rx: '1.2', opacity: '.45' }],
  ['rect', { x: '16.6', y: '5', width: '3.3', height: '14.7', rx: '1.2', opacity: '.45' }],
] as const satisfies readonly UiIconNode[];

export const priorityUrgentIcon = [
  [
    'path',
    {
      d: 'm10.6 4.5-6.1 6.1a2 2 0 0 0 0 2.8l6.1 6.1a2 2 0 0 0 2.8 0l6.1-6.1a2 2 0 0 0 0-2.8l-6.1-6.1a2 2 0 0 0-2.8 0ZM12 8.2v4.4M12 15.7h.01',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const progressIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['path', { d: 'M12 3.75V12l5.83 5.83' }],
] as const satisfies readonly UiIconNode[];

export const quoteIcon = [
  ['path', { d: 'M10 6H5v6h5v2a4 4 0 0 1-4 4M10 6v6M20 6h-5v6h5v2a4 4 0 0 1-4 4M20 6v6' }],
] as const satisfies readonly UiIconNode[];

export const rectangleIcon = [
  ['rect', { x: '4', y: '6', width: '16', height: '12', rx: '2' }],
] as const satisfies readonly UiIconNode[];

export const redo2Icon = [
  ['path', { d: 'm16 4.8 3.5 3.5-3.5 3.5M19 8.3h-8.4a6.1 6.1 0 0 0 0 12.2h3.8' }],
] as const satisfies readonly UiIconNode[];

export const referenceIcon = [
  [
    'path',
    {
      d: 'M14 5H6.5A2.5 2.5 0 0 0 4 7.5v7A2.5 2.5 0 0 0 6.5 17H8v3l4-3h5.5a2.5 2.5 0 0 0 2.5-2.5V11M8 9h4M8 12h6M17 3.5v5h4M21 4.5l-4 4',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const refreshCcwIcon = [
  [
    'path',
    {
      d: 'M19.6 9.8c-1-4.2-4.7-6.4-8.8-5.7-2.5.4-4.4 1.7-6 3.9M4.8 4.3V8h3.7M4.4 14.2c1 4.2 4.7 6.4 8.8 5.7 2.5-.4 4.4-1.7 6-3.9m0 3.7V16h-3.7',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const refreshCwIcon = [
  [
    'path',
    {
      d: 'M4.4 9.8c1-4.2 4.7-6.4 8.8-5.7 2.5.4 4.4 1.7 6 3.9m0-3.7V8h-3.7m4.1 6.2c-1 4.2-4.7 6.4-8.8 5.7-2.5-.4-4.4-1.7-6-3.9m0 3.7V16h3.7',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const regenerateIcon = [
  [
    'path',
    { d: 'M5.5 8a7.5 7.5 0 0 1 13-1M19.5 3.5v4h-4M18.5 16a7.5 7.5 0 0 1-13 1M4.5 20.5v-4h4' },
  ],
  ['path', { d: 'm12 8.5 1.1 2.4 2.4 1.1-2.4 1.1-1.1 2.4-1.1-2.4L8.5 12l2.4-1.1L12 8.5Z' }],
] as const satisfies readonly UiIconNode[];

export const removeFormattingIcon = [
  ['path', { d: 'M4.5 7V5h12v2M10.5 5l-3 13M5.5 18h4.5M15 15l5 5M20 15l-5 5' }],
] as const satisfies readonly UiIconNode[];

export const repeatIcon = [
  [
    'path',
    {
      d: 'M4.3 10V9A2.5 2.5 0 0 1 6.8 6.5h12.9m-2.7-2.7 2.7 2.7L17 9.2M19.7 14v1a2.5 2.5 0 0 1-2.5 2.5H4.3m2.7-2.7-2.7 2.7L7 20.2',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const rotateCcwIcon = [
  ['path', { d: 'M4.5 8.5a8.2 8.2 0 1 1-.2 6.6M4.5 4.5v4h4' }],
] as const satisfies readonly UiIconNode[];

export const rows3Icon = [
  ['rect', { x: '3.5', y: '3.5', width: '17', height: '17', rx: '3' }],
  ['path', { d: 'M3.5 9h17M3.5 15h17' }],
] as const satisfies readonly UiIconNode[];

export const saveIcon = [
  [
    'path',
    { d: 'M19.5 10.5v7a2 2 0 0 1-2 2h-11a2 2 0 0 1-2-2v-11a2 2 0 0 1 2-2h8l5 5M8 4.5v4h6v-4' },
  ],
  ['path', { d: 'M8 19.5v-6h8v6' }],
] as const satisfies readonly UiIconNode[];

export const scrollTextIcon = [
  [
    'path',
    {
      d: 'M5.5 8V6a2.5 2.5 0 0 1 2.5-2.5h10a2.5 2.5 0 0 1 2.5 2.5v2h-5m0-2V18a2.5 2.5 0 0 1-5 0v-2H3.5v2A2.5 2.5 0 0 0 6 20.5h7M15.5 6a2.5 2.5 0 0 1 2.5-2.5',
    },
  ],
  ['path', { d: 'M7.5 9.5h4m-4 3h4' }],
] as const satisfies readonly UiIconNode[];

export const searchIcon = [
  ['circle', { cx: '10.7', cy: '10.7', r: '6.7' }],
  ['path', { d: 'm15.5 15.5 4.7 4.7' }],
] as const satisfies readonly UiIconNode[];

export const searchXIcon = [
  ['circle', { cx: '10.7', cy: '10.7', r: '6.7' }],
  ['path', { d: 'm15.5 15.5 4.7 4.7M8.4 8.4l4.6 4.6m0-4.6-4.6 4.6' }],
] as const satisfies readonly UiIconNode[];

export const sendIcon = [
  ['path', { d: 'm3 10 17.5-6.5L14 21l-3.5-7.5L3 10ZM10.5 13.5l5-5' }],
] as const satisfies readonly UiIconNode[];

export const sendHorizontalIcon = [
  ['path', { d: 'm3.5 4 17 8-17 8 3-8-3-8ZM7 12h13' }],
] as const satisfies readonly UiIconNode[];

export const settingsIcon = [
  [
    'path',
    {
      d: 'm10 3-.6 2.2-2 .9-2.2-.6-2 3.4L5 10.5v3l-1.8 1.6 2 3.4 2.2-.6 2 .9L10 21h4l.6-2.2 2-.9 2.2.6 2-3.4-1.8-1.6v-3l1.8-1.6-2-3.4-2.2.6-2-.9L14 3h-4Z',
    },
  ],
  ['circle', { cx: '12', cy: '12', r: '3' }],
] as const satisfies readonly UiIconNode[];

export const settings2Icon = [
  ['path', { d: 'M3 6h9M17 6h4M3 18h4M12 18h9' }],
  ['circle', { cx: '14.5', cy: '6', r: '2.5' }],
  ['circle', { cx: '9.5', cy: '18', r: '2.5' }],
] as const satisfies readonly UiIconNode[];

export const shieldAlertIcon = [
  ['path', { d: 'M12 3.8 19.2 6.4v5.5c0 4-2.6 6.7-7.2 8.3-4.6-1.6-7.2-4.3-7.2-8.3V6.4Z' }],
  ['path', { d: 'M12 8v4.5M12 15.4h.01' }],
] as const satisfies readonly UiIconNode[];

export const shieldCheckIcon = [
  ['path', { d: 'M12 3.8 19.2 6.4v5.5c0 4-2.6 6.7-7.2 8.3-4.6-1.6-7.2-4.3-7.2-8.3V6.4Z' }],
  ['path', { d: 'm8.6 11.8 2.5 2.5 4.5-4.6' }],
] as const satisfies readonly UiIconNode[];

export const shieldOffIcon = [
  [
    'path',
    {
      d: 'm4.2 4.2 15.6 15.6M9.4 4.7 12 3.8l7.2 2.6v5.5c0 1.1-.2 2.2-.6 3.1M4.8 7.5v4.4c0 4 2.6 6.7 7.2 8.3 1.5-.5 2.7-1.1 3.7-1.7',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const slidersHorizontalIcon = [
  ['path', { d: 'M3 5h4M12 5h9M3 12h10M18 12h3M3 19h4M12 19h9' }],
  ['circle', { cx: '9.5', cy: '5', r: '2.5' }],
  ['circle', { cx: '15.5', cy: '12', r: '2.5' }],
  ['circle', { cx: '9.5', cy: '19', r: '2.5' }],
] as const satisfies readonly UiIconNode[];

export const slidersVerticalIcon = [
  ['path', { d: 'M5 3v4M5 12v9M12 3v10M12 18v3M19 3v4M19 12v9' }],
  ['circle', { cx: '5', cy: '9.5', r: '2.5' }],
  ['circle', { cx: '12', cy: '15.5', r: '2.5' }],
  ['circle', { cx: '19', cy: '9.5', r: '2.5' }],
] as const satisfies readonly UiIconNode[];

export const sparklesIcon = [
  [
    'path',
    {
      d: 'm10 6.5 1.8 4.7 4.7 1.8-4.7 1.8-1.8 4.7-1.8-4.7L3.5 13l4.7-1.8L10 6.5ZM18.5 3.5v4m-2-2h4M19 16v3m-1.5-1.5h3',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const squareIcon = [
  ['rect', { x: '4.25', y: '4.25', width: '15.5', height: '15.5', rx: '2.75' }],
] as const satisfies readonly UiIconNode[];

export const squareCheckIcon = [
  ['rect', { x: '4.25', y: '4.25', width: '15.5', height: '15.5', rx: '2.75' }],
  ['path', { d: 'm8.1 12.1 2.6 2.6 5.2-5.4' }],
] as const satisfies readonly UiIconNode[];

export const squareChevronRightIcon = [
  ['rect', { x: '4.25', y: '4.25', width: '15.5', height: '15.5', rx: '2.75' }],
  ['path', { d: 'm10 8.2 3.8 3.8-3.8 3.8' }],
] as const satisfies readonly UiIconNode[];

export const squarePenIcon = [
  [
    'path',
    { d: 'M11 5H6.5A2.5 2.5 0 0 0 4 7.5v10A2.5 2.5 0 0 0 6.5 20h10a2.5 2.5 0 0 0 2.5-2.5V13' },
  ],
  [
    'path',
    { d: 'm10 11.5 7-7a1.6 1.6 0 0 1 2.2 0l.8.8a1.6 1.6 0 0 1 0 2.2l-7 7-4 1 1-4ZM15.5 6l3 3' },
  ],
] as const satisfies readonly UiIconNode[];

export const squareTerminalIcon = [
  ['rect', { x: '3.5', y: '3.5', width: '17', height: '17', rx: '3' }],
  ['path', { d: 'm7.5 8.5 3.5 3.5-3.5 3.5m6-1h3' }],
] as const satisfies readonly UiIconNode[];

export const stopIcon = [
  ['rect', { x: '7.1', y: '7.1', width: '9.8', height: '9.8', rx: '2' }],
] as const satisfies readonly UiIconNode[];

export const strikethroughIcon = [
  [
    'path',
    { d: 'M17 6.5C14.3 3 6.5 4 6.5 8c0 1.5 1.2 2.5 3.5 3.1M17.3 14.5c1 5.5-8.4 7-11 3.2M4 12h16' },
  ],
] as const satisfies readonly UiIconNode[];

export const sunIcon = [
  ['circle', { cx: '12', cy: '12', r: '4' }],
  [
    'path',
    { d: 'M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.4 1.4M17.6 17.6 19 19M5 19l1.4-1.4M17.6 6.4 19 5' },
  ],
] as const satisfies readonly UiIconNode[];

export const table2Icon = [
  ['rect', { x: '3', y: '4', width: '18', height: '16', rx: '2.5' }],
  ['path', { d: 'M3 9h18M9 9v11M15 9v11M3 14.5h18' }],
] as const satisfies readonly UiIconNode[];

export const tagIcon = [
  ['path', { d: 'M4 4h7l9 9a1.5 1.5 0 0 1 0 2l-5 5a1.5 1.5 0 0 1-2 0l-9-9V4Z' }],
  ['circle', { cx: '8', cy: '8', r: '1' }],
] as const satisfies readonly UiIconNode[];

export const targetIcon = [
  ['circle', { cx: '12', cy: '12', r: '8.25' }],
  ['circle', { cx: '12', cy: '12', r: '4.1' }],
  ['path', { d: 'M12 12h.01' }],
] as const satisfies readonly UiIconNode[];

export const terminalIcon = [
  ['rect', { x: '3.5', y: '5', width: '17', height: '14', rx: '2.5' }],
  ['path', { d: 'm7 9 3.5 3-3.5 3m6 .5h4' }],
] as const satisfies readonly UiIconNode[];

export const timerResetIcon = [
  [
    'path',
    {
      d: 'M9.6 3.8h4.8M12 3.8v1.5M5.548 9.025a7.45 7.45 0 1 1-.744 5.653M5.548 5.525v3.5h3.5M12 9.4v3.35l2.6 1.6',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const trash2Icon = [
  [
    'path',
    {
      d: 'M3.5 6.5h17M9 6.5V3.5h6v3M5.5 6.5l.7 12a2 2 0 0 0 2 2h7.6a2 2 0 0 0 2-2l.7-12M10 10.5v6M14 10.5v6',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const triangleIcon = [
  ['path', { d: 'm12 4.5 8 14H4l8-14Z' }],
] as const satisfies readonly UiIconNode[];

export const triangleAlertIcon = [
  [
    'path',
    {
      d: 'M10.5 5.1a1.7 1.7 0 0 1 3 0L19.8 17c.7 1.3-.2 2.8-1.7 2.8H5.9c-1.5 0-2.4-1.5-1.7-2.8ZM12 9.1v4.1M12 16.1h.01',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const typeIcon = [
  ['path', { d: 'M6 7V4.5h12V7M12 4.5v15M9 19.5h6' }],
] as const satisfies readonly UiIconNode[];

export const undo2Icon = [
  ['path', { d: 'm8 4.8-3.5 3.5L8 11.8M5 8.3h8.4a6.1 6.1 0 0 1 0 12.2H9.6' }],
] as const satisfies readonly UiIconNode[];

export const unlinkIcon = [
  [
    'path',
    {
      d: 'M9 7l2.5-2.5a5 5 0 0 1 7 7L16 14M8 10l-2.5 2.5a5 5 0 0 0 7 7L15 17M9 3V1.5M3 9H1.5M15 21v1.5M21 15h1.5',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const uploadIcon = [
  ['path', { d: 'M4.5 15.5v2a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2v-2M12 14.5v-10m-4 4 4-4 4 4' }],
] as const satisfies readonly UiIconNode[];

export const userIcon = [
  ['circle', { cx: '12', cy: '7', r: '3.5' }],
  ['path', { d: 'M4.5 20v-2a4 4 0 0 1 4-4h7a4 4 0 0 1 4 4v2' }],
] as const satisfies readonly UiIconNode[];

export const userRoundIcon = [
  ['circle', { cx: '12', cy: '7', r: '3.5' }],
  ['path', { d: 'M4.5 20c0-8 15-8 15 0' }],
] as const satisfies readonly UiIconNode[];

export const userRoundCogIcon = [
  ['circle', { cx: '9', cy: '7', r: '3.5' }],
  [
    'path',
    {
      d: 'M2.5 20c0-4.5 5-7 8.5-5.5M17 11.5v2M17 20.5v2M11.5 17h2M20.5 17h2M13.2 13.2l1.4 1.4M19.4 19.4l1.4 1.4M13.2 20.8l1.4-1.4M19.4 14.6l1.4-1.4',
    },
  ],
  ['circle', { cx: '17', cy: '17', r: '3.5' }],
] as const satisfies readonly UiIconNode[];

export const usersIcon = [
  ['circle', { cx: '9', cy: '7', r: '3.5' }],
  [
    'path',
    {
      d: 'M2.5 20v-2a4 4 0 0 1 4-4h5a4 4 0 0 1 4 4v2M16 3.5a3.5 3.5 0 0 1 0 7M18 14a4 4 0 0 1 3.5 4v2',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const wifiOffIcon = [
  [
    'path',
    {
      d: 'M8 5.8A16 16 0 0 1 21 9M3 9l1-.7M12 10a11 11 0 0 1 5.5 2M6.5 12l1.3-.7M9.5 15.5a4.5 4.5 0 0 1 4-.5M12 19v.2M3 3l18 18',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const workflowIcon = [
  ['rect', { x: '3', y: '3', width: '6', height: '6', rx: '1.8' }],
  ['rect', { x: '15', y: '15', width: '6', height: '6', rx: '1.8' }],
  ['path', { d: 'M9 6h5a4 4 0 0 1 4 4v5M6 12v6h6' }],
] as const satisfies readonly UiIconNode[];

export const worktreeIcon = [
  ['rect', { x: '3.5', y: '4', width: '6', height: '5', rx: '2' }],
  ['rect', { x: '14.5', y: '4', width: '6', height: '5', rx: '2' }],
  ['circle', { cx: '12', cy: '18.5', r: '2' }],
  ['path', { d: 'M6.5 9v1c0 4 5.5 1.5 5.5 6.5M17.5 9v1c0 4-5.5 1.5-5.5 6.5' }],
] as const satisfies readonly UiIconNode[];

export const wrapTextIcon = [
  ['path', { d: 'M3 5h18M3 11h14a4 4 0 0 1 0 8h-6M3 18h3M13 16l-3 3 3 3' }],
] as const satisfies readonly UiIconNode[];

export const wrenchIcon = [
  [
    'path',
    {
      d: 'M20.5 8.5a6 6 0 0 1-7.5 7L7 21a2.5 2.5 0 0 1-3.5-3.5l5.5-6a6 6 0 0 1 7-7.5L12.5 7l.5 3 3 .5 4.5-2Z',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const xIcon = [
  ['path', { d: 'm6.5 6.5 11 11m0-11-11 11' }],
] as const satisfies readonly UiIconNode[];

export const zapIcon = [
  ['path', { d: 'm13.5 3.9-8 9.3h5.8l-.8 6.9 8-9.3h-5.8Z' }],
] as const satisfies readonly UiIconNode[];

export const zapOffIcon = [
  [
    'path',
    {
      d: 'm4.2 4.2 15.6 15.6M9.1 8.6l4.4-4.7-.8 6.9h5.8l-3.1 3.5m-2.1 2.3-2.8 3.5.8-6.9H5.5l1.2-1.4',
    },
  ],
] as const satisfies readonly UiIconNode[];

export const zoomInIcon = [
  ['circle', { cx: '10.5', cy: '10.5', r: '6.5' }],
  ['path', { d: 'm15.5 15.5 4.5 4.5M10.5 7.5v6M7.5 10.5h6' }],
] as const satisfies readonly UiIconNode[];

export const zoomOutIcon = [
  ['circle', { cx: '10.5', cy: '10.5', r: '6.5' }],
  ['path', { d: 'm15.5 15.5 4.5 4.5M7.5 10.5h6' }],
] as const satisfies readonly UiIconNode[];
